Repository neutrons/PyRS, pull requests merged in 2020-02, with the labels that each got.

#344 Allow for not having selected row
  pyrs/interface/peak_fitting/event_handler.py
  pyrs/interface/peak_fitting/gui_utilities.py
Labels: bug, gui

#345 Fix uncertainty of peak center in pseudo-Voigt
  pyrs/core/peak_profile_utility.py
  tests/unit/test_peak_collection.py
Labels: bug

#372 Python3 fixes
  pyrs/core/summary_generator.py
  tests/integration/test_manual_reduction_ui.py
  tests/integration/test_peak_fitting.py
  tests/unit/test_peak_fit_engine.py
Labels: bug

#385 Fix error in calculation of d-spacing from 2theta
  pyrs/peaks/peak_collection.py
  tests/unit/test_peak_collection.py
Labels: bug

#388 Fall back to finddata when ArchiveSearch fails
  pyrs/utilities/file_util.py
  tests/unit/test_utilities.py
Labels: bug

#390 Monosetting enum
  pyrs/calibration/peakfit_calibration.py
  pyrs/core/__init__.py
  pyrs/core/monosetting.py
  pyrs/core/nexus_conversion.py
  tests/integration/test_calibration_class.py
  tests/unit/test_monosetting.py
Labels: minor enhancement
